defmodule ShinjukuEx do
  use Dynamo.App

  endpoint ApplicationRouter

  config :dynamo,
    # The OTP application associated to this app
    # This is the name of the .app file generated by mix
    otp_app: :shinjuku_ex,
    # The route from where public assets are served
    # You can turn off static assets by setting it to false
    static_route: "/static"

  # Default functionality available in views
  views do
    use Dynamo.Helpers
  end

  initializer :start_otp_app do
    :application.start config[:dynamo][:otp_app]
  end
end
